import re

LABS = [
    "Ai2", "Allen Institute for AI",
    "Apollo Research",
    "Arc Institute",
    "Anthropic",
    "Alignment Research Center",
    "UK AI Security Institute", "UK AI Safety Institute",
    "Berkeley BAIR", "Berkeley Artificial Intelligence Research",
    "Berkeley CHAI", "Center for Human-Compatible AI",
    "Carnegie Mellon University", "CMU",
    "Cyber Valley",
    "DFKI", "Deutsches Forschungszentrum für Künstliche Intelligenz",
    "ELLIS Institute", "ELLIS Network",
    "FAR.AI",
    "FutureHouse",
    "Goodfire",
    "Google DeepMind", "DeepMind",
    "Kempner Institute",
    "Institute for Protein Design",
    "Isomorphic Labs",
    "KE:SAI",
    "Kyutai",
    "Latent Labs",
    "Liquid AI",
    "Meta FAIR", "Fundamental AI Research", "Meta AI",
    "METR", "Model Evaluation & Threat Research",
    "Mila", "Quebec AI Institute",
    "MIT CSAIL",
    "Max Planck Institute for Intelligent Systems", "MPI-IS",
    "Microsoft Research",
    "OpenAI",
    "Periodic Labs",
    "Physical Intelligence",
    "Redwood Research",
    "RIKEN AIP",
    "Sakana AI",
    "Santa Fe Institute",
    "Stanford AI Lab", "Stanford CRFM", "Stanford HAI",
    "Toyota Research Institute",
    "Tübingen AI Center",
    "Vector Institute",
    "xAI"
]

